# SITE SETTINGS
title: Aloft
description: "Bird movement data from European weather radars"

# SOCIAL PROFILES
# None set

# THEME SETTINGS
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish@2.0
tweets_on_home: false
colors:
  links: "#295cc9"
  banner: "#282949"
  footer: "#0d1626"
font_serif: false

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/news/:year/:slug/"
