# SITE SETTINGS
title: Aloft

# SOCIAL PROFILES
# None set

# THEME SETTINGS
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish@3.0
pages_on_home: # Custom attribute for _layouts/home.html
  - visualize.md
  - browse.md
tweets_on_home: false
github_edit: true
colors:
  links: "#295cc9"
  banner: "#282949"
  footer: "#0d1626"
font_serif: false

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
# None set
